embedding_models:
  jina:
    name: "jinaai/jina-embeddings-v2-base-en"
    type: "huggingface"
    embedding_size: 768
    max_length: 8192
  openai:
    name: "text-embedding-ada-002"
    type: "openai"
    embedding_size: 1536
    max_length: 8191
    api_key: "${OPENAI_API_KEY}"  # Will be loaded from environment variable

default_model: "jina"  # Can be "jina" or "openai"
